### ISSUE TITLE
Uncaught TypeError: Cannot read property 'mutateSelectedText' of undefined

### ISSUE THREAD

**Issue by syabruk** [jmoses/atom-smarter-delete-line#2]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 0.184.0
**System**: Mac OS X 10.10.2
**Thrown From**: [smarter-delete-line](https://github.com/jmoses/atom-smarter-delete-line) package, v1.0.0
### Stack Trace

Uncaught TypeError: Cannot read property 'mutateSelectedText' of undefined

```
At /Users/SeTeM/.atom/packages/smarter-delete-line/lib/smarter-delete-line.coffee:6

TypeError: Cannot read property 'mutateSelectedText' of undefined
  at atom-text-editor.<anonymous> (/Users/SeTeM/.atom/packages/smarter-delete-line/lib/smarter-delete-line.coffee:6:13)
  at atom-text-editor.handler (/Applications/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:115:32)
  at atom-workspace.jQuery.event.dispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/Applications/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at /Applications/Atom.app/Contents/Resources/app/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:558:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app/node_modules/atom-keymap/lib/keymap-manager.js:396:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (/Applications/Atom.app/Contents/Resources/app/src/window-event-handler.js:182:20)

```
### Commands

```
     -8:03.9 AtomPair:hide views (atom-text-editor.editor.mini.is-focused)
     -8:02.6 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
     -8:01.0 core:backspace (atom-text-editor.editor.mini.is-focused)
     -8:00.7 core:select-all (atom-text-editor.editor.mini.is-focused)
     -8:00.5 core:backspace (atom-text-editor.editor.mini.is-focused)
     -7:57.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -7:54.9 core:copy (atom-text-editor.editor.is-focused)
     -7:36.6 fuzzy-finder:toggle-file-finder (atom-text-editor.editor.is-focused)
     -7:35.0 project-find:show (atom-text-editor.editor.mini.is-focused)
     -7:33.6 core:paste (atom-text-editor.editor.mini)
     -7:33.4 core:confirm (atom-text-editor.editor.mini)
 14x -0:11.1 core:close (ol.results-view.list-tree.focusable-panel.has-collapsable-children)
     -0:03.4 fuzzy-finder:toggle-file-finder (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-one-dark-syntax.theme-one-dark-ui)
  2x -0:02.3 core:backspace (atom-text-editor.editor.mini.is-focused)
     -0:02.1 smarter-delete-line:delete-to-first-character (atom-text-editor.editor.mini.is-focused)
  2x -0:01.3 core:backspace (atom-text-editor.editor.mini.is-focused)
```
### Config

``` json
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store .hg",
      ".bundle",
      ".DS_Store",
      ".live-archive"
    ],
    "followSymlinks": true,
    "disabledPackages": [
      "wrap-guide",
      "autosave",
      "autocomplete",
      "regex-railroad-diagram",
      "go-plus"
    ],
    "themes": [
      "one-dark-ui",
      "one-dark-syntax"
    ],
    "projectHome": "/Users/SeTeM/projects"
  }
}
```
### Installed Packages

``` coffee
# User
atom-pair, v0.37.0
autocomplete-plus, v2.4.0
autocomplete-snippets, v1.0.1
compare-files, v0.4.1
editor-stats, v0.17.0
file-icons, v1.5.0
file-types, v0.3.0
filetype-color, v0.1.4
language-docker, v1.1.2
language-haml, v0.15.0
language-rspec, v0.3.0
language-slim, v0.3.0
language-textile, v0.2.0
linter, v0.12.0
live-archive, v0.1.13
markdown-table-formatter, v2.5.2
pain-split, v1.3.1
pretty-json, v0.3.2
ruby-slim, v0.2.0
smarter-delete-line, v1.0.0
symbols-tree-view, v0.6.1

# Dev
No dev packages
```

**Comment by jmoses** [comment]
Heh, I just saw this. I should turn on notifications. :/

Can you update the latest version and try again?  I just updated to the v1 APIs, so maybe that sorted your issue.
